#include "stm32f4xx_hal.h"
#include "main.h"
#include "chassis.h"
#include "gimbal.h"
#include "remote.h"
#include "config.h"
#include <string.h>

/* System state */
static robot_state_e robot_state = ROBOT_STOP;
static chassis_mode_e chassis_mode_request = CHASSIS_MODE_INDEPENDENT;

/* Timer handles (assumed to be initialized by CubeMX) */
extern TIM_HandleTypeDef htim6;  /* 1kHz control task timer */
extern TIM_HandleTypeDef htim7;  /* LED indicator timer */

/* LED breathing effect variables */
static uint32_t led1_breath_counter = 0;
static uint32_t led2_flash_counter = 0;
static const uint32_t LED1_BREATH_PERIOD = 2000; /* 2s breathing cycle */

/**
 * Hardware Initialization (called from CubeMX)
 */
void SystemClock_Config(void)
{
    /* RCC_OscInitTypeDef and RCC_ClkInitTypeDef configuration */
    /* This would be generated by CubeMX */
}

void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* LED pins */
    GPIO_InitStruct.Pin = LED1_Pin | LED2_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(LED1_GPIO_Port, &GPIO_InitStruct);

    /* Button pins */
    GPIO_InitStruct.Pin = KEY1_Pin | KEY2_Pin | KEY3_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Pull = GPIO_PULLUP;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(KEY1_GPIO_Port, &GPIO_InitStruct);
}

void MX_TIM6_Init(void)
{
    /* 1kHz timer interrupt for control task */
    htim6.Instance = TIM6;
    htim6.Init.Prescaler = 84 - 1;  /* 84MHz / 84 = 1MHz */
    htim6.Init.CounterMode = TIM_COUNTERMODE_UP;
    htim6.Init.Period = 1000 - 1;   /* 1MHz / 1000 = 1kHz */
    htim6.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
    HAL_TIM_Base_Init(&htim6);
    HAL_TIM_Base_Start_IT(&htim6);
}

void MX_TIM7_Init(void)
{
    /* 100Hz timer for LED indicator */
    htim7.Instance = TIM7;
    htim7.Init.Prescaler = 84 - 1;  /* 84MHz / 84 = 1MHz */
    htim7.Init.CounterMode = TIM_COUNTERMODE_UP;
    htim7.Init.Period = 10000 - 1;  /* 1MHz / 10000 = 100Hz */
    htim7.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
    HAL_TIM_Base_Init(&htim7);
    HAL_TIM_Base_Start_IT(&htim7);
}

/**
 * LED Indicator Control
 * L1: Breathing effect (system running indicator)
 * L2: Mode indicator (1Hz for normal, 2Hz for spin, etc.)
 */
static void LED_Update(void)
{
    static uint8_t breath_direction = 1;
    static uint8_t brightness = 0;

    /* L1: Breathing LED effect */
    led1_breath_counter++;
    if (led1_breath_counter < 500) {
        brightness = (led1_breath_counter * 255) / 500;
    } else if (led1_breath_counter < 1000) {
        brightness = (255 * (1000 - led1_breath_counter)) / 500;
    } else {
        led1_breath_counter = 0;
    }

    if (brightness > 128) {
        HAL_GPIO_WritePin(LED1_GPIO_Port, LED1_Pin, GPIO_PIN_SET);
    } else {
        HAL_GPIO_WritePin(LED1_GPIO_Port, LED1_Pin, GPIO_PIN_RESET);
    }

    /* L2: Mode indicator flash */
    led2_flash_counter++;
    uint32_t flash_period = 1000; /* Default 1Hz for normal mode */

    switch (chassis_mode_request) {
        case CHASSIS_MODE_SPIN:
            flash_period = 500;  /* 2Hz for spin mode */
            break;
        case CHASSIS_MODE_FOLLOW:
            flash_period = 333;  /* 3Hz for follow mode */
            break;
        default:
            flash_period = 1000; /* 1Hz for independent mode */
            break;
    }

    if (led2_flash_counter % (flash_period / 10) < (flash_period / 20)) {
        HAL_GPIO_WritePin(LED2_GPIO_Port, LED2_Pin, GPIO_PIN_SET);
    } else {
        HAL_GPIO_WritePin(LED2_GPIO_Port, LED2_Pin, GPIO_PIN_RESET);
    }

    if (led2_flash_counter >= 10000) {
        led2_flash_counter = 0;
    }
}

/**
 * Mode and State Machine Management
 */
static void StateMachine_Update(void)
{
    static bool key1_prev = false;
    static bool key2_prev = false;
    static bool key3_prev = false;

    /* State transitions */
    if (remote.key1_pressed && !key1_prev) {
        /* Toggle robot state */
        if (robot_state == ROBOT_STOP) {
            robot_state = ROBOT_NORMAL;
        } else {
            robot_state = ROBOT_STOP;
        }
    }

    /* Chassis mode control */
    if (remote.key1_long_press) {
        chassis_mode_request = CHASSIS_MODE_FOLLOW;
    } else if (remote.key1_pressed && !remote.key1_long_press) {
        chassis_mode_request = CHASSIS_MODE_SPIN;
    } else {
        chassis_mode_request = CHASSIS_MODE_INDEPENDENT;
    }

    /* Gimbal yaw control with key2 */
    if (remote.key2_pressed) {
        float current_yaw = gimbal.yaw_target;
        Gimbal_SetYawTarget(current_yaw + remote.yaw_increment);
    }

    /* Gimbal pitch control with key3 */
    if (remote.key3_pressed) {
        float current_pitch = gimbal.pitch_target;
        Gimbal_SetPitchTarget(current_pitch + remote.pitch_increment);
    }

    key1_prev = remote.key1_pressed;
    key2_prev = remote.key2_pressed;
    key3_prev = remote.key3_pressed;
}

/**
 * Main Control Task - Called at 1kHz from TIM6 interrupt
 */
static void Control_Task(void)
{
    /* Update sensor inputs */
    Remote_Update();

    /* Execute state machine */
    StateMachine_Update();

    /* Control logic based on robot state */
    switch (robot_state) {
        case ROBOT_STOP:
            Chassis_Stop();
            Gimbal_Stop();
            break;

        case ROBOT_NORMAL:
            /* Update chassis with current mode */
            Chassis_SetMode(chassis_mode_request);
            Chassis_Update(gimbal.yaw_angle);

            /* Update gimbal */
            Gimbal_Update();

            /* Safety: Check for motor stall */
            // TODO: Implement motor stall detection

            break;
    }
}

/**
 * TIM6 Interrupt Handler - 1kHz control task
 */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == TIM6) {
        Control_Task();
    } else if (htim->Instance == TIM7) {
        LED_Update();
    }
}

/**
 * Main Entry Point
 */
int main(void)
{
    /* Initialize HAL */
    HAL_Init();
    SystemClock_Config();

    /* Initialize peripherals */
    MX_GPIO_Init();
    MX_TIM6_Init();
    MX_TIM7_Init();

    /* Initialize modules */
    Chassis_Init();
    Gimbal_Init();
    Remote_Init();

    /* Set initial states */
    robot_state = ROBOT_STOP;
    Gimbal_SetYawTarget(0);
    Gimbal_SetPitchTarget(0);

    /* Main loop */
    while (1) {
        /* The control task runs in TIM6 interrupt at 1kHz */
        /* This loop can be used for low-priority background tasks */
        
        /* Example: Low-priority logging or data transmission */
        // Serial_SendDebugData();
    }

    return 0;
}

/**
 * Error Handler
 */
void Error_Handler(void)
{
    __disable_irq();
    while (1) {
        HAL_GPIO_TogglePin(LED1_GPIO_Port, LED1_Pin);
        HAL_Delay(100);
    }
}
